#!/bin/bash

source="/home/xxx/"
destination="/home/xxx/"
listePhoto=`ls $source*.jpg 2>/dev/null`

if [[ $listePhoto ]]; then
for photo in $listePhoto;
do
        date=`echo $photo | cut -c16-21`
        echo "Fichier en cours: $date"
        if [ ! -d "$date" ];then
                echo "Creation de: $date"
                mkdir $date
        fi
                mv $photo "$destination$date"
done
fi
