#!/bin/bash

source="/home/xxx/tmp/"
destination="/home/xxx/disk1/"
listePhoto=`ls $source*.jpg 2>/dev/null`

if [[ $listePhoto ]]; then
for photo in $listePhoto;
do
        photoEnCours=`echo $photo | cut -c16-32`
        date=`echo $photo | cut -c16-21`
#        echo "Fichier en cours: $photoEnCours"
        if [ ! -d "$destination$date" ];then
#                echo "Creation de: $destination$date"
                mkdir $destination$date
        fi
                mv $photo "$destination$date/$photoEnCours"
done
fi

exit 0
